language: node_js
node_js:
  - '8'

branches:
  only:
    - master
    - develop
    - /greenkeeper\/.*/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  - npm i -g npm
  - npm i -g cordova ionic

script:
  - npm run lint
